name: producttypeimport
type: module
core: 8.x
dependencies:
  - commerce
  - commerce_price
  - commerce_product
  - facets
  - field
  - field_group
  - file
  - filefield_paths
  - image
  - language
  - path
  - svg_image
  - tablefield
  - tablefield_required
  - taxonomy
  - text
core_incompatible: false
